import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
import HeaderOrganizer from '@/components/HeaderOrganizer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Event Celebrated',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          {/* <div className="flex h-screen flex-col"> */}
          {/* <HeaderOrganizer /> */}
          <main className="flex-1">{children}</main>
          {/* <main className="flex-1">{children}</main> */}
          {/* <Footer></Footer> */}
        </div>
      </body>
    </html>
  );
}
